### ISSUE TITLE
Scroll to Error Field?

### ISSUE THREAD

**Issue by rodneypoplin** [eltimn/jquery-bs-formalerts#1]
How would I add something like this?
$(document).ready(function(){
    $('form[data-toggle="validator"]').on('submit', function (e) {
        var errors = $('.has-error')
        if (errors.length) {
            $(document).scrollTop(errors.offset().top)
        }
    });
});

I want it to scroll up to the field with the error on a very long form.

**Comment by eltimn** [comment]
Your call to (".has-error") returns an array, so you'll need to find the smallest value in that array.

This is the code I use to do the same, with help from [lodash](https://lodash.com/):

```
var elems = _.map($("div.has-error"), function(elem) {
  return $(elem).offset().top;
});

var top = _.min(elems);

if (_.isNumber(top)) {
  window.scrollTo(0, top-60);
}
```

I had to subtract 60 to get it to scroll to the proper spot with the css/html from my site. You may need to tweak that.
